src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProductRepository::class)
 * @ORM\HasLifecycleCallbacks()
 */
class Product
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $name;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @ORM\Column(type="date")
     */
    private $createdAt;

    /**
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="products")
     */
    private $category;

    /**
     * Méthode exécutée avant l'insertion en base
     * @ORM\PrePersist()
     */
    public function prePersist(){
        if ($this->createdAt ===null){
            $this->createdAt = new \DateTime();
        }
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    /**
     * Obtenir le prix en décimal: 1500->15.00
     */
    public function getPriceFloat(): ?float
    {
        return $this->price === null ? null : $this->price / 100;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }
}

src/Controller/AdminProductController.php
<?php

namespace App\Controller;

use App\Entity\Product;
use App\Form\ConfirmDeletionFormType;
use App\Form\ProductFormType;
use App\Repository\ProductRepository;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

/**
 * N'autoriser l'accès qu'aux administrateurs sur toutes les routes de ce controlleur
 * @IsGranted("ROLE_ADMIN")
 *
 * Spécifier un préfixe d'URI et de nom de route:
 * @Route("/admin/product",  name="admin_product_")
 */
class AdminProductController extends AbstractController
{
    /**
     * Liste des produits. On combine l'annotation Route de la classe avec celle de la méthode
     *     URI: /admin/products
     *     name: admin_product_list
     * @Route("s", name="list")
     */
    public function index(ProductRepository $repository)
    {
        $products = $repository->findAll();
        return $this->render('admin_product/index.html.twig', [
            'product_list' => $products
        ]);
    }

    /**
     * @Route("/new", name="add")
     */
    public function add(Request $request, EntityManagerInterface $entityManager){
        $form = $this->createForm(ProductFormType::class);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()){
            $product = $form->getData();
            $entityManager->persist($product);
            $entityManager->flush();

            $this->addFlash('success', 'Le produit a été enregistrer');
            return $this->redirectToRoute('admin_product_list');
        }

        return $this->render('admin_product/add.html.twig', [
            'product_form' => $form->createView()
        ]);
    }

    /**
     * @Route("/{id}/edit", name="edit")
     */
    public function edit(Product $product, Request $request, EntityManagerInterface $entityManager){
        $form = $this->createForm(ProductFormType::class, $product);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()){
            $entityManager->flush();
            $this->addFlash('success', 'Modifications enregistrées');
        }

        return $this->render('admin_product/edit.html.twig', [
            'product' => $product,
            'product_form' => $form->createView()
        ]);
    }

    /**
     * @Route("/{id}/delete", name="delete")
     */
    public function delete(Product $product, Request $request, EntityManagerInterface $entityManager){
        $form = $this->createForm(ConfirmDeletionFormType::class);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()){
            //A l'inverse de persist(), remove() prépare à la suppression d'une entité
            $entityManager->remove($product);
            $entityManager->flush();

            $this->addFlash('success', 'Le produit a été supprimmé');
            return $this->redirectToRoute('admin_product_list');
        }
        return $this->render('admin_product/delete.html.twig', [
            'product' => $product,
            'deletion_form' => $form->createView()
        ]);
    }
}

templates/admin_product/_product_form.html.twig
{{ form_start(product_form) }}

        {{ form_row(product_form.name, {
            label: 'Nom du produit:'
        }) }}

        {{ form_row(product_form.category, {
            label: 'Catégorie du produit:'
        }) }}

        {{ form_row(product_form.description, {
            label: 'Description du produit:'
        }) }}

        {{ form_row(product_form.price, {
            label: 'Prix:'
        }) }}

<button type="submit" class="button is-success is-fullwidth">
    Enregistrer
</button>

{{ form_end(product_form) }}

templates/admin_product/add.html.twig
{% extends "_admin_template.html.twig" %}

{% block title %}
    Nouveau produit
{% endblock %}

{% block content %}
    <div class="section">
        <h1 class="title">Nouveau produit</h1>

        {% include 'admin_product/_product_form.html.twig' %}
    </div>

{% endblock %}

templates/admin_product/delete.html.twig
{% extends "_admin_template.html.twig" %}

{% block title %}
    Supprimer le produit {{ product.name }}
{% endblock %}

{% block content %}
    <div class="section">
        <h1 class="title">Supprimer le produit {{ product.name }}</h1>

        {{ form_start(deletion_form) }}

        {{ form_row(deletion_form.confirmation, {
            label: 'Je confirme la suppression du produit"' ~ product.name ~ '"'
        }) }}

        <button type="submit" class="button is-danger is-fullwidth">
            Supprimer
        </button>

        {{ form_end(deletion_form) }}

    </div>
{% endblock %}

templates/admin_product/edit.html.twig
{% extends "_admin_template.html.twig" %}

{% block title %}
    Moodifier le produit {{ product.name }}

{% endblock %}

{% block content %}
    <div class="section">
        <h1 class="title">Modifier le produit {{ product.name }}</h1>
        <h2 class="subtitle">Créé le {{ product.createdAt|date('d/m/Y') }}</h2>

        {% include 'includes/flashes.html.twig' %}
        
        {% include 'admin_product/_product_form.html.twig' %}
    </div>

{% endblock %}

templates/admin_product/index.html.twig
{% extends "_admin_template.html.twig" %}

{% block title %}
    Liste des produits
{% endblock %}

{% block content %}
    <div class="section">
        <h1 class="title">Liste des produits: </h1>

        {% include "includes/flashes.html.twig" %}

        <a href="{{ path('admin_product_add') }}" class="button is-success mb-4">
            Nouveau produit
        </a>

        <table class="table is-fullwidth">
            <thead>
            <tr>
                <th>#</th>
                <th>Nom</th>
                <th>Description</th>
                <th>Catégorie</th>
                <th>Prix</th>
                <th>Création</th>
            </tr>
            </thead>
            <tbody>
            {% for product in product_list %}
                <tr>
                    <td>{{ product.id }}</td>
                    <td>
                        <a href="{{ path('product_show', {id: product.id}) }}" target="_blank">
                            {{ product.name }}
                        </a>
                    </td>
                    <td>{{ product.description|slice(0, 25) }}</td>
                    <td>{{ product.category.getName() }}</td>
                    <td class="has-text-right">
                        {{ product.priceFloat|number_format(2, '.', ' ') }} €
                    </td>
                    <td>{{ product.createdAt|date('d/m/Y') }}</td>
                    <td>
                        <div class="buttons">
                            <a href="{{ path('admin_product_edit', {id: product.id}) }}" class="button is-success">Modifier</a>
                            <a href="{{ path('admin_product_delete', {id: product.id}) }}" class="button is-danger">Supprimer</a>
                        </div>
                    </td>
                </tr>
            {% endfor %}

            </tbody>
        </table>
    </div>
{% endblock %}